spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voteDB?serverTimezone=UTC
    username: yujin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false